enum FeatureFlags {
  FEATURE_FLAGS = 'FEATURE_FLAGS',
  SETTINGS = 'SETTINGS',
  USER_MANAGEMENT = 'USER_MANAGEMENT',
  USER_REGISTERATION = 'USER_REGISTRATION',
  VENDOR_CLIENTELE = 'VENDOR_CLIENTELE',
}

export default FeatureFlags;
